// AUTO-GENERATED by update-scores workflow. Do not edit manually.
// Last updated: 2026-06-17T07:43:21.113Z
// Matches with results: 20
const MATCH_SCORES = {
  "Mexico|South Africa": {
    "score": {
      "home": 2,
      "away": 0
    }
  },
  "South Korea|Czech Republic": {
    "score": {
      "home": 2,
      "away": 1
    }
  },
  "Canada|Bosnia and Herzegovina": {
    "score": {
      "home": 1,
      "away": 1
    }
  },
  "United States|Paraguay": {
    "score": {
      "home": 4,
      "away": 1
    }
  },
  "Qatar|Switzerland": {
    "score": {
      "home": 1,
      "away": 1
    }
  },
  "Brazil|Morocco": {
    "score": {
      "home": 1,
      "away": 1
    }
  },
  "Haiti|Scotland": {
    "score": {
      "home": 0,
      "away": 1
    }
  },
  "Australia|Turkey": {
    "score": {
      "home": 2,
      "away": 0
    }
  },
  "Germany|Curaçao": {
    "score": {
      "home": 7,
      "away": 1
    }
  },
  "Netherlands|Japan": {
    "score": {
      "home": 2,
      "away": 2
    }
  },
  "Ivory Coast|Ecuador": {
    "score": {
      "home": 1,
      "away": 0
    }
  },
  "Sweden|Tunisia": {
    "score": {
      "home": 5,
      "away": 1
    }
  },
  "Spain|Cape Verde Islands": {
    "score": {
      "home": 0,
      "away": 0
    }
  },
  "Belgium|Egypt": {
    "score": {
      "home": 1,
      "away": 1
    }
  },
  "Saudi Arabia|Uruguay": {
    "score": {
      "home": 1,
      "away": 1
    }
  },
  "Iran|New Zealand": {
    "score": {
      "home": 2,
      "away": 2
    }
  },
  "France|Senegal": {
    "score": {
      "home": 3,
      "away": 1
    }
  },
  "Iraq|Norway": {
    "score": {
      "home": 1,
      "away": 4
    }
  },
  "Argentina|Algeria": {
    "score": {
      "home": 3,
      "away": 0
    }
  },
  "Austria|Jordan": {
    "score": {
      "home": 3,
      "away": 1
    }
  }
};
