// AUTO-GENERATED by update-scores workflow. Do not edit manually.
// Last updated: 2026-06-25T07:10:56.298Z
// Matches with results: 54
const MATCH_SCORES = {
  "Mexico|South Africa": {
    "score": {
      "home": 2,
      "away": 0
    }
  },
  "South Korea|Czech Republic": {
    "score": {
      "home": 2,
      "away": 1
    }
  },
  "Canada|Bosnia and Herzegovina": {
    "score": {
      "home": 1,
      "away": 1
    }
  },
  "United States|Paraguay": {
    "score": {
      "home": 4,
      "away": 1
    }
  },
  "Qatar|Switzerland": {
    "score": {
      "home": 1,
      "away": 1
    }
  },
  "Brazil|Morocco": {
    "score": {
      "home": 1,
      "away": 1
    }
  },
  "Haiti|Scotland": {
    "score": {
      "home": 0,
      "away": 1
    }
  },
  "Australia|Turkey": {
    "score": {
      "home": 2,
      "away": 0
    }
  },
  "Germany|Curaçao": {
    "score": {
      "home": 7,
      "away": 1
    }
  },
  "Netherlands|Japan": {
    "score": {
      "home": 2,
      "away": 2
    }
  },
  "Ivory Coast|Ecuador": {
    "score": {
      "home": 1,
      "away": 0
    }
  },
  "Sweden|Tunisia": {
    "score": {
      "home": 5,
      "away": 1
    }
  },
  "Spain|Cape Verde Islands": {
    "score": {
      "home": 0,
      "away": 0
    }
  },
  "Belgium|Egypt": {
    "score": {
      "home": 1,
      "away": 1
    }
  },
  "Saudi Arabia|Uruguay": {
    "score": {
      "home": 1,
      "away": 1
    }
  },
  "Iran|New Zealand": {
    "score": {
      "home": 2,
      "away": 2
    }
  },
  "France|Senegal": {
    "score": {
      "home": 3,
      "away": 1
    }
  },
  "Iraq|Norway": {
    "score": {
      "home": 1,
      "away": 4
    }
  },
  "Argentina|Algeria": {
    "score": {
      "home": 3,
      "away": 0
    }
  },
  "Austria|Jordan": {
    "score": {
      "home": 3,
      "away": 1
    }
  },
  "Portugal|DR Congo": {
    "score": {
      "home": 1,
      "away": 1
    }
  },
  "England|Croatia": {
    "score": {
      "home": 4,
      "away": 2
    }
  },
  "Ghana|Panama": {
    "score": {
      "home": 1,
      "away": 0
    }
  },
  "Uzbekistan|Colombia": {
    "score": {
      "home": 1,
      "away": 3
    }
  },
  "Czech Republic|South Africa": {
    "score": {
      "home": 1,
      "away": 1
    }
  },
  "Switzerland|Bosnia and Herzegovina": {
    "score": {
      "home": 4,
      "away": 1
    }
  },
  "Canada|Qatar": {
    "score": {
      "home": 6,
      "away": 0
    }
  },
  "Mexico|South Korea": {
    "score": {
      "home": 1,
      "away": 0
    }
  },
  "United States|Australia": {
    "score": {
      "home": 2,
      "away": 0
    }
  },
  "Scotland|Morocco": {
    "score": {
      "home": 0,
      "away": 1
    }
  },
  "Brazil|Haiti": {
    "score": {
      "home": 3,
      "away": 0
    }
  },
  "Turkey|Paraguay": {
    "score": {
      "home": 0,
      "away": 1
    }
  },
  "Netherlands|Sweden": {
    "score": {
      "home": 5,
      "away": 1
    }
  },
  "Germany|Ivory Coast": {
    "score": {
      "home": 2,
      "away": 1
    }
  },
  "Ecuador|Curaçao": {
    "score": {
      "home": 0,
      "away": 0
    }
  },
  "Tunisia|Japan": {
    "score": {
      "home": 0,
      "away": 4
    }
  },
  "Spain|Saudi Arabia": {
    "score": {
      "home": 4,
      "away": 0
    }
  },
  "Belgium|Iran": {
    "score": {
      "home": 0,
      "away": 0
    }
  },
  "Uruguay|Cape Verde Islands": {
    "score": {
      "home": 2,
      "away": 2
    }
  },
  "New Zealand|Egypt": {
    "score": {
      "home": 1,
      "away": 3
    }
  },
  "Argentina|Austria": {
    "score": {
      "home": 2,
      "away": 0
    }
  },
  "France|Iraq": {
    "score": {
      "home": 3,
      "away": 0
    }
  },
  "Norway|Senegal": {
    "score": {
      "home": 3,
      "away": 2
    }
  },
  "Jordan|Algeria": {
    "score": {
      "home": 1,
      "away": 2
    }
  },
  "Portugal|Uzbekistan": {
    "score": {
      "home": 5,
      "away": 0
    }
  },
  "England|Ghana": {
    "score": {
      "home": 0,
      "away": 0
    }
  },
  "Panama|Croatia": {
    "score": {
      "home": 0,
      "away": 1
    }
  },
  "Colombia|DR Congo": {
    "score": {
      "home": 1,
      "away": 0
    }
  },
  "Switzerland|Canada": {
    "score": {
      "home": 2,
      "away": 1
    }
  },
  "Bosnia and Herzegovina|Qatar": {
    "score": {
      "home": 3,
      "away": 1
    }
  },
  "Morocco|Haiti": {
    "score": {
      "home": 4,
      "away": 2
    }
  },
  "Scotland|Brazil": {
    "score": {
      "home": 0,
      "away": 3
    }
  },
  "Czech Republic|Mexico": {
    "score": {
      "home": 0,
      "away": 3
    }
  },
  "South Africa|South Korea": {
    "score": {
      "home": 1,
      "away": 0
    }
  }
};
